name: Send Discord Webhook with Commit URL

on:
  push:
    branches:
      - main

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord webhook with commit details
        env:
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          COMMIT_TITLE=$(echo "$COMMIT_MESSAGE" | head -n 1)
          COMMIT_DESCRIPTION=$(echo "$COMMIT_MESSAGE" | tail -n +2)

          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"@everyone New commit pushed: ${COMMIT_URL}\nCheck out the website: <https://jaymakesvideos.xyz>\n\n\`\`\`\n${COMMIT_TITLE}\n\n${COMMIT_DESCRIPTION}\n\`\`\`\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
