name: Send Discord Webhook with Commit URL

on:
  push:
    branches:
      - main

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord webhook with commit details
        env:
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          COMMIT_TITLE=$(echo "$COMMIT_MESSAGE" | head -n 1)
          COMMIT_DESCRIPTION=$(echo "$COMMIT_MESSAGE" | tail -n +2 | sed ':a;N;$!ba;s/\n/\\n/g')

          # Ensure the description is not empty
          if [ -z "$COMMIT_DESCRIPTION" ]; then
            COMMIT_DESCRIPTION="(No additional description)"
          fi

          # Escape special characters for JSON
          COMMIT_TITLE=$(echo "$COMMIT_TITLE" | sed 's/"/\\"/g')
          COMMIT_DESCRIPTION=$(echo "$COMMIT_DESCRIPTION" | sed 's/"/\\"/g')

          # Construct JSON payload manually
          JSON_PAYLOAD="{\"content\": \"@everyone New commit pushed: ${COMMIT_URL}\\nCheck out the website: <https://jaymakesvideos.xyz>\\n\\n\`\`\`${COMMIT_TITLE}\\n\\n${COMMIT_DESCRIPTION}\`\`\`\"}"

          echo "Sending payload: $JSON_PAYLOAD" # Debugging line

          curl -X POST \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
