name: Send Discord Webhook with Commit Details

on:
  push:
    branches:
      - main

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord webhook with commit details
        env:
          COMMIT_DETAILS: ${{ toJson(github.event.head_commit) }}
          REF: ${{ github.ref }}
          SHA: ${{ github.sha }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"New commit pushed on ${REF} with SHA ${SHA}.\\nCommit details: ${COMMIT_DETAILS}\"}" \
            https://discord.com/api/webhooks/1348146455185195018/PEawKLhT8rlgfP_aRc0IIVDJXn0LNi-OneKnEcSNwX1UF0gE2QzkHjxgrG0XV1-tks8s
