name: Send Discord Webhook with Commit URL

on:
  push:
    branches:
      - main

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord webhook with commit details
        env:
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          COMMIT_TITLE=$(echo "$COMMIT_MESSAGE" | head -n 1)
          COMMIT_DESCRIPTION=$(echo "$COMMIT_MESSAGE" | tail -n +2)

          # Ensure description is not empty
          if [ -z "$COMMIT_DESCRIPTION" ]; then
            COMMIT_DESCRIPTION="(No additional description)"
          fi

          # Format the message correctly
          JSON_PAYLOAD=$(jq -n \
            --arg url "$COMMIT_URL" \
            --arg title "$COMMIT_TITLE" \
            --arg desc "$COMMIT_DESCRIPTION" \
            --arg site "https://jaymakesvideos.xyz" \
            '{content: "@everyone New commit pushed: " + $url + "\nCheck out the website: <" + $site + ">\n\n```" + $title + "\n\n" + $desc + "```"}')

          echo "Sending payload: $JSON_PAYLOAD" # Debugging line

          curl -X POST \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
